package autojotter.gui;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.io.StringReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Jae
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainWindow() {
        initComponents();
        recalcParams();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInput = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        chkSVGOutput = new javax.swing.JCheckBox();
        chkRotate90 = new javax.swing.JCheckBox();
        chkItalics = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txtCharWidth = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        txtCharHeight = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtUp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDown = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFeedRate = new javax.swing.JSpinner();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtWidth = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        txtColumns = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        txtRows = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGcodeOutput = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnSaveFile = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AutoJotter by Jae F. Muzzin");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/icon.png")).getImage());
        setMinimumSize(new java.awt.Dimension(800, 537));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Input Text:");
        getContentPane().add(jLabel1);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(286, 150));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(286, 150));

        txtInput.setColumns(40);
        txtInput.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtInput.setTabSize(5);
        txtInput.setMinimumSize(new java.awt.Dimension(324, 544));
        jScrollPane1.setViewportView(txtInput);

        getContentPane().add(jScrollPane1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setMinimumSize(new java.awt.Dimension(498, 60));
        jPanel1.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

        chkSVGOutput.setText("SVG Output (Uncheck for Gcode)");
        jPanel10.add(chkSVGOutput);

        chkRotate90.setSelected(true);
        chkRotate90.setText("Rotate 90");
        chkRotate90.setToolTipText("Use this if your pen plotter has a wider X axis.  Rotates the page to make maximum use of plotter area.");
        jPanel10.add(chkRotate90);

        chkItalics.setSelected(true);
        chkItalics.setText("Italics");
        jPanel10.add(chkItalics);

        jLabel11.setText("Character Width (in):");
        jPanel10.add(jLabel11);

        txtCharWidth.setModel(new javax.swing.SpinnerNumberModel(0.125d, 0.0d, null, 0.025d));
        txtCharWidth.setEnabled(false);
        txtCharWidth.setMinimumSize(new java.awt.Dimension(50, 20));
        txtCharWidth.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel10.add(txtCharWidth);

        jLabel12.setText("Character Height (in):");
        jPanel10.add(jLabel12);

        txtCharHeight.setModel(new javax.swing.SpinnerNumberModel(0.25d, 0.0d, null, 0.05d));
        txtCharHeight.setPreferredSize(new java.awt.Dimension(50, 20));
        txtCharHeight.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtCharHeightStateChanged(evt);
            }
        });
        jPanel10.add(txtCharHeight);

        jPanel1.add(jPanel10, java.awt.BorderLayout.WEST);

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jLabel7.setText("Pen Up Command:");
        jPanel9.add(jLabel7);

        txtUp.setText("M3 S400");
        txtUp.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel9.add(txtUp);

        jLabel6.setText("Pen Down Command:");
        jPanel9.add(jLabel6);

        txtDown.setText("M3 S850");
        txtDown.setToolTipText("");
        txtDown.setPreferredSize(new java.awt.Dimension(60, 20));
        txtDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDownActionPerformed(evt);
            }
        });
        jPanel9.add(txtDown);

        jLabel10.setText("Writing Rate (in/min)");
        jPanel9.add(jLabel10);

        txtFeedRate.setModel(new javax.swing.SpinnerNumberModel(50, 1, null, 1));
        jPanel9.add(txtFeedRate);

        jPanel1.add(jPanel9, java.awt.BorderLayout.EAST);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));

        jLabel3.setText("Total Width (in):");
        jPanel11.add(jLabel3);

        txtWidth.setModel(new javax.swing.SpinnerNumberModel(6.0d, 0.0d, null, 1.0d));
        txtWidth.setEnabled(false);
        txtWidth.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel11.add(txtWidth);

        jLabel2.setText("Total Height (in):");
        jPanel11.add(jLabel2);

        txtHeight.setModel(new javax.swing.SpinnerNumberModel(1.5d, 0.0d, null, 0.3d));
        txtHeight.setEnabled(false);
        txtHeight.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel11.add(txtHeight);

        jLabel4.setText("Character Columns:");
        jPanel11.add(jLabel4);

        txtColumns.setModel(new javax.swing.SpinnerNumberModel(40, 0, null, 1));
        txtColumns.setPreferredSize(new java.awt.Dimension(50, 20));
        txtColumns.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtColumnsStateChanged(evt);
            }
        });
        jPanel11.add(txtColumns);

        jLabel5.setText("Character Rows:");
        jPanel11.add(jLabel5);

        txtRows.setModel(new javax.swing.SpinnerNumberModel(5, 0, null, 1));
        txtRows.setPreferredSize(new java.awt.Dimension(50, 20));
        txtRows.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtRowsStateChanged(evt);
            }
        });
        jPanel11.add(txtRows);

        jPanel1.add(jPanel11, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setMinimumSize(new java.awt.Dimension(164, 170));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(164, 170));

        txtGcodeOutput.setColumns(20);
        txtGcodeOutput.setRows(8);
        txtGcodeOutput.setTabSize(5);
        jScrollPane2.setViewportView(txtGcodeOutput);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Output File:");
        jPanel5.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jButton1.setText("Generate File");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        btnSaveFile.setText("Save File");
        btnSaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveFileActionPerformed(evt);
            }
        });
        jPanel3.add(btnSaveFile);

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jPanel2.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtColumnsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtColumnsStateChanged
        recalcParams();
    }//GEN-LAST:event_txtColumnsStateChanged

    private void txtRowsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtRowsStateChanged
        recalcParams();
    }//GEN-LAST:event_txtRowsStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ByteArrayOutputStream outBytes = new ByteArrayOutputStream();
        PrintStream out = new PrintStream(outBytes);
        ByteArrayOutputStream errBytes = new ByteArrayOutputStream();
        PrintStream err = new PrintStream(errBytes);
        try {
            autojotter.AutoJotter.run((double) txtWidth.getValue(), (double) txtHeight.getValue(), (int) txtColumns.getValue(),
                    (int) txtRows.getValue(), txtUp.getText(), txtDown.getText(), (Integer) txtFeedRate.getValue(), chkRotate90.isSelected(), chkItalics.isSelected(), chkSVGOutput.isSelected(),
                    out, err, new BufferedReader(new StringReader(txtInput.getText())));
            txtGcodeOutput.setText(new String(outBytes.toByteArray()));
            JOptionPane.showMessageDialog(this, "This is a preview of your formatted text:\r\n\r\n" + new String(errBytes.toByteArray()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDownActionPerformed

    private void txtCharHeightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtCharHeightStateChanged
        // TODO add your handling code here:
        recalcParams();
    }//GEN-LAST:event_txtCharHeightStateChanged

    private void btnSaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose save location");        
        fileChooser.setSelectedFile(new File("output." + (chkSVGOutput.isSelected() ? "svg" : "ngc")));
        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            System.out.println("Save as file: " + fileToSave.getAbsolutePath());
            try{
            PrintWriter pw = new PrintWriter(new FileOutputStream(fileToSave));
            pw.write(txtGcodeOutput.getText());
            pw.flush();
            pw.close();
                JOptionPane.showMessageDialog(this, "Saved to "+fileToSave.getAbsolutePath());
            }catch(FileNotFoundException e){
                JOptionPane.showMessageDialog(this, "File not found, please select different location");
            }
        }
    }//GEN-LAST:event_btnSaveFileActionPerformed
    private void recalcParams() {
        txtCharWidth.getModel().setValue((Double) txtCharHeight.getValue() / 2);
        txtWidth.getModel().setValue(((Double) txtCharWidth.getValue()) * (int) txtColumns.getValue());
        txtHeight.getModel().setValue(((Double) txtCharHeight.getValue()) * (int) txtRows.getValue());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(
                    javax.swing.UIManager.getSystemLookAndFeelClassName());
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveFile;
    private javax.swing.JCheckBox chkItalics;
    private javax.swing.JCheckBox chkRotate90;
    private javax.swing.JCheckBox chkSVGOutput;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner txtCharHeight;
    private javax.swing.JSpinner txtCharWidth;
    private javax.swing.JSpinner txtColumns;
    private javax.swing.JTextField txtDown;
    private javax.swing.JSpinner txtFeedRate;
    private javax.swing.JTextArea txtGcodeOutput;
    private javax.swing.JSpinner txtHeight;
    private javax.swing.JTextArea txtInput;
    private javax.swing.JSpinner txtRows;
    private javax.swing.JTextField txtUp;
    private javax.swing.JSpinner txtWidth;
    // End of variables declaration//GEN-END:variables
}
